name: repy
channels:
  - defaults
  - conda-forge
dependencies:
  - python==3.7.2
  - pip==18.1
  - setuptools==40.6.3
  - pytest==4.1.1
  - pylint==2.2.2
  - flake8==3.6.0
  - pudb==2018.1
  - ipython==7.2.0
  - coverage==4.5.2
  - nose==1.3.7
  - mypy==0.660
