---
swagger: "2.0"
info:
  description: "This is just a test file"
  version: "0.0.6"
  title: "none"
basePath: "/v1"
tags:
- name: "none"
  description: "test"
  externalDocs:
    description: "Find out more"
    url: "http://github.com/campanja/repy"
schemes:
- "https"
- "http"
paths:
  /bla/{bla_id}:
    get:
      summary: "test"
      description: "test"
      operationId: "test"
      produces:
      - "application/json"
      parameters:
      - name: "bla_id"
        in: "path"
        description: "id of the bla"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Bla"
        400:
          description: "Invalid request parameter supplied"
        404:
          description: "Test not found"
        500:
          description: "Internal server error"
definitions:
  Bla:
    type: "object"
    required:
    - "bla_data"
    properties:
      bla_data:
        type: "string"
        description: "The bla response"
externalDocs:
  description: "Find out more"
  url: "http://github.com/campanja/repy"
